# Generated by Django 2.2.2 on 2019-07-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('long_url', models.URLField()),
                ('short_url_subpart', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
