# Generated by Django 2.2.2 on 2019-07-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url_subpart',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='url',
            name='user_id',
            field=models.CharField(default=None, max_length=16),
        ),
    ]
