# Generated by Django 2.2.2 on 2019-07-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0002_auto_20190703_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url_subpart',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='user_id',
            field=models.CharField(max_length=16),
        ),
    ]
