# Generated by Django 2.2.2 on 2019-07-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0003_auto_20190703_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url_subpart',
            field=models.SlugField(blank=True, default='short_url'),
        ),
    ]
