# Generated by Django 2.2.2 on 2019-07-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0004_auto_20190703_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url_subpart',
            field=models.SlugField(blank=True, default='subpart'),
        ),
    ]
