# Generated by Django 2.1.7 on 2019-07-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0005_auto_20190703_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url_subpart',
            field=models.SlugField(blank=True, default='subpart', unique=True),
        ),
    ]
