# Generated by Django 2.1.7 on 2020-01-17 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BlockItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object_id', models.IntegerField()),
                ('content_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='MainPageBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.IntegerField(choices=[('1', 'Обычный блок (изображение, текст)'), ('2', 'Цитата'), ('3', 'Средний блок'), ('4', 'Средний квадратный блок'), ('5', 'Большой блок'), ('6', 'Фотореп блок'), ('7', 'Широкий блок с новостями'), ('8', 'Эволюция'), ('9', 'Колонка с новостями'), ('10', 'Блок-баннер'), ('11', 'Блок-баннер для адаптива')], default=1, verbose_name='Тип блока')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='blockitem',
            name='mainpageblock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='matrixblock.MainPageBlock'),
        ),
    ]
